<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.trionesdev.commons</groupId>
        <artifactId>triones-commons</artifactId>
        <version>0.0.2-SNAPSHOT</version>
    </parent>

    <artifactId>commons</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>commons-core</module>
        <module>commons-exception</module>
        <module>commons-mybatis-plus</module>
        <module>commons-context</module>
        <module>commons-i18n</module>
        <module>commons-feign</module>
        <module>commons-lock</module>
    </modules>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.trionesdev.commons</groupId>
                <artifactId>commons-dependencies</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>